## Exploitation de données

#### Monthly_Modal_Time_series.csv

In [3]:
import pandas as pd

file_path = r"C:\Users\ahmed\OneDrive\Bureau\Projet LogiOps360\logiOps360\logiOps360\Transport\Data\Monthly_Modal_Time_Series_20250611.csv"
df_modal = pd.read_csv(file_path)
df_modal.head()

,NTD ID,Agency,Organization Type,Mode,Type of Service,Rail (True/False),Primary UZA UACE Code,Primary UZA Name,Primary UZA Sq Miles,Primary UZA Population,...,Non-Major Physical Assaults on Operators,Non-Major Non-Physical Assaults on Operators,Non-Major Physical Assaults on Other Transit Workers,Non-Major Non-Physical Assaults on Other Transit Workers,Major Physical Assaults on Operators,Major Non-Physical Assaults on Operators,Major Physical Assaults on Other Transit Workers,Major Non-Physical Assaults on Other Transit Workers,Total Assaults on Transit Workers,MoYr
0,20008,MTA New York City Transit,"Unit of a Transit Agency, Reporting Separately",HR,DO,True,63217.0,"New York--Jersey City--Newark, NY--NJ",3248.12,19426449.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20140101
1,20008,MTA New York City Transit,"Unit of a Transit Agency, Reporting Separately",HR,DO,True,63217.0,"New York--Jersey City--Newark, NY--NJ",3248.12,19426449.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20140201
2,20008,MTA New York City Transit,"Unit of a Transit Agency, Reporting Separately",HR,DO,True,63217.0,"New York--Jersey City--Newark, NY--NJ",3248.12,19426449.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20140301
3,20008,MTA New York City Transit,"Unit of a Transit Agency, Reporting Separately",HR,DO,True,63217.0,"New York--Jersey City--Newark, NY--NJ",3248.12,19426449.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20140401
4,20008,MTA New York City Transit,"Unit of a Transit Agency, Reporting Separately",HR,DO,True,63217.0,"New York--Jersey City--Newark, NY--NJ",3248.12,19426449.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20140501

In [6]:
null_percent = df_modal.isnull().mean() * 100
null_percent

NTD ID                                                   0.000000
Agency                                                   0.000000
Organization Type                                        5.850481
Mode                                                     0.000000
Type of Service                                          0.000000
                                                          ...
Major Non-Physical Assaults on Operators                87.345212
Major Physical Assaults on Other Transit Workers        87.345212
Major Non-Physical Assaults on Other Transit Workers    87.345212
Total Assaults on Transit Workers                       87.322708
MoYr                                                     0.000000
Length: 75, dtype: float64

In [8]:
df_modal.describe()

,NTD ID,Primary UZA UACE Code,Primary UZA Sq Miles,Primary UZA Population,Service Area Sq Miles,Service Area Population,Year,Month_Year (timestamp),VOMS,Vehicle Revenue Miles,...,Non-Major Physical Assaults on Operators,Non-Major Non-Physical Assaults on Operators,Non-Major Physical Assaults on Other Transit Workers,Non-Major Non-Physical Assaults on Other Transit Workers,Major Physical Assaults on Operators,Major Non-Physical Assaults on Operators,Major Physical Assaults on Other Transit Workers,Major Non-Physical Assaults on Other Transit Workers,Total Assaults on Transit Workers,MoYr
count,173302.000000,168506.000000,168506.000000,1.685060e+05,163233.000000,1.632330e+05,173302.000000,173302.000000,172527.000000,1.725270e+05,...,9714.000000,9714.000000,9714.000000,9714.000000,21931.000000,21931.000000,21931.000000,21931.000000,21970.000000,1.733020e+05
mean,48207.838092,50651.905968,650.528859,2.689918e+06,674.729712,9.662606e+05,2019.172497,201923.634367,74.263141,2.333539e+05,...,0.608709,1.682005,0.317789,0.338892,0.037344,0.001049,0.023711,0.000182,1.365362,2.019236e+07
std,27783.991288,28467.925360,805.078650,4.503735e+06,1954.114286,1.728051e+06,3.277675,327.574979,232.936837,9.758813e+05,...,2.072894,7.114069,1.611691,1.588929,0.415961,0.033747,0.432264,0.013504,6.506950,3.275750e+04
min,1.000000,42.000000,0.000000,5.025400e+04,1.000000,5.443000e+03,2014.000000,201401.000000,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014010e+07
25%,30034.000000,23527.000000,91.850000,2.241560e+05,75.000000,1.562970e+05,2016.000000,201610.000000,9.000000,2.078850e+04,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.016100e+07
50%,50008.000000,52390.000000,300.420000,6.847730e+05,251.000000,3.421420e+05,2019.000000,201908.000000,22.000000,5.957100e+04,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.019080e+07
75%,70008.000000,77068.000000,906.640000,3.070300e+06,664.000000,9.272840e+05,2022.000000,202206.000000,53.000000,1.602605e+05,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.022060e+07
max,99425.000000,99999.000000,3248.120000,1.942645e+07,121697.000000,2.196212e+07,2025.000000,202504.000000,5429.000000,3.083597e+07,...,44.000000,131.000000,49.000000,35.000000,17.000000,2.000000,21.000000,1.000000,154.000000,2.025040e+07

In [9]:
distinct_counts = df_modal.nunique()
print(distinct_counts)

for col in df_modal.columns:
    print(f"\nColumn: {col}")
    print(df_modal[col].unique())

NTD ID                                                  631
Agency                                                  629
Organization Type                                        11
Mode                                                     16
Type of Service                                           4
                                                       ...
Major Non-Physical Assaults on Operators                  3
Major Physical Assaults on Other Transit Workers         18
Major Non-Physical Assaults on Other Transit Workers      2
Total Assaults on Transit Workers                       101
MoYr                                                    136
Length: 75, dtype: int64

Column: NTD ID
[20008 20217 30102 90044 90024 90157 90039 40037 40029 40179 60041 20193
 20075 30103 30058 30051 10117 10005 50141    29    40    35 90003 90134
 90009 50154 40200 90031 90086 70006     8 90224 30078 50143 40222 10045
 40196 10042 10050 60124 40171 30014 60033 90035 30025 40043 50158 70003
 90171 60010 40044 40014 10088 90020 30002 10051 50051 20003 30001 80004
 70045 80028    57 80009 40068 50009 30095 90230 30012 30026 90226 20199
 60134 50211 20206 20076 20175 90214 90147 50066 50131 40152 60084 90169
 90209 90131 50193    54 90193 90095 30022 50117 70035 50161 50096 10064
 40007 10017 10108 10056 10057 10107 90228 50165 90119 40002 10055 70015
 40192 40097 90164 40093 50044 40009 20178 70001 70049 60009    49 10087
 50002 50035 40092 30072 90006 50059 70014 40047 80016 50047 90061 90062
 90093 20185 30088 10066 70012 10061 50110 30045 50148    43 30107 30094
 90175 80008 70041 30035 90149 40026 30074 40185 20072 20084 20071 20078
 50179 60133 30075 30068 40153 40135 10053 10004 90016 40074 40027 50146
 90090 90196 30044 70005 50016 10048 10063 40018 40169 60019 40110 50033
 40141     2 10008 20116 20172 40001 30018 60072 90079 40173 80025 50024
 20010 20137 10105 50032 90089 40005 40030 50043 60059 30013 90091 90173
 50060 70016    21 70018 70019 90208 50099 70048 30076 80107 50061 90201
 90142 40057 30091 10119 40100 90200 60082 20177 20099 90043 90042 90023
 90022 50182 50113 50042 50167 40077 60103 60114 30019 30071 30080 10013
 50119 90159 50155 80109 90045 90205 40105 30101 50050 50012 50160 10001
 10102 70002 60018 50017 60022 70010 50021 90078 10126 90001 40053 90148
 90162 50040 50011 60024 40144 50056    19 40172 10128 70008 90087 40180
 90233 70030 50092 50184 50054 50053 90219    44 90241 40046 20135 20149
 20188 90211 90010 90008 50045 60008 40082 10118 90034     3 90234 40041
 90242 40175 50157 50166 40019 50191 50199 50008 40003 20004 60127 90033
 60006 60111 90027 50169 80005 40028 90004 10049 50005 90012 40108 40038
 90007 50197 50036 40025 90017 40224 50052 40031     7    25 60091 40127
 80003 60001 10016 40088 60012 11154 50006 50028 40103 50029 80012    47
 90213 10007 30087 90002 20203 40128 20132 20122 20169 20080 20096 20192
 90036 90146 50183 50103 30081 40078 40203 40022 90140     5 90029 30048
    58 60011 40094 40086 40178 60017 10130 60088 40042 50010 90144 60101
 20018 40087 30015 40071 80011 40017 50058    18    12 30027    20 50026
 90232 10040 10006 40158     6 50025 40021 50034 30054 30096 30011 50088
 40058 30077 30061 20128 20098 20166 20161 20163 20160 20189 20165 20190
 20126 40034 60007 20204 30030 40138 10003 90032    23 90014    24 90019
 40035 90013 30023 40040 80001 40159 30006 20113 30010 20002 10014    11
 40140 40012 40051 60051 80106 50057 40006 40036 80002 40120    34 90092
 60016 50004 60077 50163 40191 60107 50145 20145 90206 90156 40104 40032
 40129 90154 90041 60056 30070 30085 90136 50031    28     1 90225 90015
 90026 90030 50027 30034 60130 90223 60048 30111 50198 50015 30083 40008
 40004 60020 40063 50022 40023 40015 30055 40102 30024 50001 60038 30007
 60014 50149 50003 30008 80007 50039 60102 90088    16 50159 90121 30137
 20082 20196 20006 90166 80006 60032 90244 60095 22930 40147 41068 40230
 44929 50516 10086 20209 10129 50517 40245 60090 40244 30112 40163 10183
 50515 50519 50518 90296 99425 99423 90229 70044 40258 40259 40208 91092
 10098 90222 30129 50521 30201 41105 40928 50204 11147 70271 40228   415
    46 60269 50213 40265 30202 50522   376 99422 99424 40950 90218 40264
 50342 55312 50209 90094 90302 40247 66339 50176 70066 55311 11239 80285
 20226 11238 70275 20223 42000 60108 41199 90306 30205 70138 20228 70057
 60015 60270 60276 90310 90311 60273 30206 20230 40252 31036 91059 30207
 91122 90313 70009 90303 40056 40954 50413 40271 60246 40209 90299 50571
 11160 40130 50093 20212 50020 41090 70133]

Column: Agency
['MTA New York City Transit' 'Hampton Jitney, Inc.' 'Martz Trailways'
 'City of Arcadia' 'City of La Mirada' 'Access Services'
 'City of Culver City' 'Board of County Commissioners, Palm Beach County'
 'Broward County Board of County Commissioners'
 'Broward County Community Bus Service' 'City of Arlington'
 'Cumberland County' 'Port Authority Transit Corporation'
 'Martz Group, National Coach Works of Virginia' 'City of Fairfax'
 'Montgomery County, Maryland'
 'Plymouth & Brockton Street Railway Company'
 'Lowell Regional Transit Authority' 'Detroit Transportation Corporation'
 'Snohomish County Public Transportation Benefit Area Corporation'
 'Central Puget Sound Regional Transit Authority'
 'Washington State Ferries'
 'San Francisco Bay Area Rapid Transit District'
 'Peninsula Corridor Joint Powers Board'
 'San Mateo County Transit District' 'Metropolitan Council'
 'Tampa Bay Area Regional Transit Authority' 'Riverside Transit Agency'
 'City of Riverside'
 'Bi-State Development Agency of the Missouri-Illinois Metropolitan District'
 'Tri-County Metropolitan Transportation District of Oregon'
 'Paratransit, Inc. CTSA' 'Southwestern Pennsylvania Commission'
 'Brunswick Transit Alternative' 'Wake County'
 'Connecticut Department of Transportation - CTTransit New Britain -Dattco.'
 'Kentuckiana Regional Planning and Development Agency'
 'Valley Transit District' 'Greater Bridgeport Transit Authority'
 'vRide, Inc. - El Paso'
 'Knoxville-Knox County Community Action Committee'
 'Cumberland Dauphin-Harrisburg Transit Authority'
 'Rock Region Metropolitan Transit Authority'
 'Gold Coast Transit District' 'County of Lackawanna Transit System'
 'City of Mobile'
 'University of Michigan Parking and Transportation Services'
 'City of Springfield' 'City of Santa Clarita' 'City of Lubbock'
 'City of Montgomery' 'Ms Coast Transportation Authority'
 'Casco Bay Island Transit District'
 'Santa Barbara Metropolitan Transit District'
 'The Tri-State Transit Authority' 'Housatonic Area Regional Transit'
 'Greater Lafayette Public Transportation Corporation' 'Broome County'
 'Kanawha Valley Regional Transportation Authority' 'City of Billings'
 'County of Johnson, Iowa' 'Cache Valley Transit District'
 'Central Oregon Intergovernmental Council'
 'Missoula Urban Transportation District'
 'Northwest Alabama Council of Local Governments'
 'City of Oshkosh, Wisconsin' 'County of Lebanon Transit Authority'
 'California Vanpool Authority' 'Cambria County Transit Authority'
 'River Valley Transit Authority'
 'Imperial County Transportation Commission' 'County of Atlantic'
 'The Woodlands Township' 'Rides Mass Transit District' 'County of Nassau'
 'Westchester County' 'Private Transportation Corporation'
 'City of Redondo Beach' 'City of Los Angeles' 'Chicago Transit Authority'
 'Opportunity Enterprises, Inc.' 'Miami Lakes - vRide, Inc.'
 'Ft.Worth - vRide, Inc.' 'vRide, Inc. - Valley Metro'
 'Valley Metro Rail, Inc.' 'City of Scottsdale'
 'Michigan Department of Transportation' 'King County Ferry District'
 'Chula Vista Transit' 'San Diego Association of Governments'
 'Pittsburgh Regional Transit' 'Laketran' 'Johnson County Kansas'
 'Ozaukee County' 'City of Waukesha'
 'Greater Attleboro-Taunton Regional Transit Authority' 'City of Raleigh'
 'Greater Hartford Transit District'
 'Greater Hartford Ridesharing Corporation - The Rideshare Company'
 'Connecticut Department of Transportation - CTTRANSIT Stamford Division'
 'Norwalk Transit District' 'Milford Transit District'
 'vRide, Inc. - Tucson' 'Greene County Transit Board'
 'City of Laguna Beach' 'City of Knoxville'
 'Connecticut Department of Transportation - CTTRANSIT New Haven Division'
 'City of Wichita' 'Martin County' 'Council on Aging of St. Lucie, Inc.'
 'Ventura County Transportation Commission' 'City of Greensboro'
 'Fort Wayne Public Transportation Corporation' 'City of Fayetteville'
 'Ulster County' 'City of Lincoln' 'River Bend Transit' 'City of Laredo'
 'vRide, Inc. - Anchorage' 'City of Nashua' 'City of Green Bay'
 'Central County Transportation Authority' 'City of Clarksville'
 'Frederick County, Maryland' 'Santa Cruz Metropolitan Transit District'
 'Springfield Mass Transit District'
 'Topeka Metropolitan Transit Authority'
 'Athens-Clarke County Unified Government' 'County of Mesa'
 'Bloomington-Normal Public Transit System'
 'Yuba-Sutter Transit Authority' 'Monterey-Salinas Transit'
 'Redding Area Bus Authority' 'Centro of Oneida, Inc.'
 'County Commissioners of Charles County, MD'
 'Green Mountain Transit Authority' 'City of Sioux City'
 'Montachusett Regional Transit Authority'
 'Bloomington Public Transportation Corporation' 'JAUNT, Inc.'
 'Blue Water Area Transportation Commission' 'Chelan Douglas PTBA'
 'West Virginia University' 'City of Harrisonburg' 'City of Lodi'
 'City of Grand Forks' 'Ames Transit Agency'
 'Ohio Valley Regional Transportation Authority' 'City of Lompoc'
 'Manatee County Board of County Commissioners' 'Harford County Maryland'
 'Bay County Transportation Planning Organization' 'Suffolk County'
 'County of Rockland' 'Town of Huntington'
 'Metro-North Commuter Railroad Company, dba: MTA Metro-North Railroad'
 'Porter County Aging and Community Services, Inc.'
 'McKinney Avenue Transit Authority' 'Delaware Transit Corporation'
 'Fairfax County, VA' 'vRide, Inc. - Atlanta'
 'Georgia Regional Transportation Authority'
 'Cape Ann Transportation Authority' 'Brockton Area Transit Authority'
 'Golden Gate Bridge, Highway and Transportation District'
 'Pasco County Board of County Commissioners'
 'Pinellas Suncoast Transit Authority' 'Madison County Transit District'
 'Yolo County Transportation District' 'County of Placer'
 'Westmoreland County Transit Authority'
 'Kansas City Area Transportation Authority'
 'Central Ohio Transit Authority'
 'Connecticut Department of Transportation - CTTRANSIT - Hartford Division'
 'Middletown Transit District' 'Transit Authority of River City'
 'Regional Planning Commission of Greater Birmingham'
 'City of Albuquerque' 'Charleston Area Regional Transportation Authority'
 'Interurban Transit Partnership'
 'Central Midlands Regional Transportation Authority'
 'Spokane Transit Authority' 'Pioneer Valley Transit Authority'
 'Centro of Cayuga, Inc.' 'Centro of Oswego, Inc.'
 'Chattanooga Area Regional Transportation Authority'
 'Red Rose Transit Authority' 'Ozark Regional Transit'
 'SunLine Transit Agency' 'Piedmont Authority for Regional Transportation'
 'City of Loveland, Colorado' 'Western Reserve Transit Authority'
 'Dutchess County' 'Monroe Bus Corporation'
 'Cape Cod Regional Transit Authority' 'Mass Transportation Authority'
 'County of Sonoma' 'City of Asheville' 'City of Gainesville, FL'
 'City of Evansville' 'Brazos Transit District'
 'Erie Metropolitan Transit Authority' 'City of Visalia'
 'Transit Joint Powers Authority for Merced County'
 'Champaign-Urbana Mass Transit District' 'City of Columbia'
 'Whatcom Transportation Authority' 'City of Iowa City'
 'University of Iowa' 'Butte County Association of Governments'
 'City of Eau Claire' 'City of Lawrence'
 'Williamsburg Area Transit Authority' 'University of Montana'
 'City of Decatur, Il' 'City of Turlock' 'University of California, Davis'
 'Jackson Transit Authority' 'Town of Blacksburg'
 'University Of New Hampshire'
 'Santee Wateree Regional Transportation Authority'
 'Kings County Area Public Transit Agency' 'The Gulf Coast Center'
 'Adirondack Transit Lines, Inc.'
 'Staten Island Rapid Transit Operating Authority' 'City of Commerce'
 'City of Gardena' 'Long Beach Transit' 'City of Norwalk'
 'Pace, the Suburban Bus Division of the Regional Transportation Authority'
 'City of East Chicago' 'South Lake County Community Services, Inc.'
 'South Florida Regional Transportation Authority'
 'Fort Bend County, Texas' 'STAR Transit'
 'Southeastern Pennsylvania Transportation Authority' 'City of Alexandria'
 'Arlington County, Virginia'
 'Merrimack Valley Regional Transit Authority' 'City of Detroit'
 'Western Contra Costa Transit Authority' 'Metro Mobility'
 'Denver Regional Council of Governments'
 'Regional Transportation Commission of Southern Nevada'
 'City of Elk Grove' 'Puerto Rico Highway and Transportation Authority'
 'City of Washington'
 'Indianapolis and Marion County Public Transportation'
 'Southwest Ohio Regional Transit Authority' 'County of Washington'
 'Rhode Island Public Transit Authority'
 'Connecticut Department of Transportation' 'Transit Authority of Omaha'
 'Metropolitan Tulsa Transit Authority'
 'Greater Dayton Regional Transit Authority' 'Capital Area Transit System'
 'Des Moines Area Regional Transit Authority'
 'Portage Area Regional Transportation Authority'
 'Central Contra Costa Transit Authority'
 'Worcester Regional Transit Authority COA'
 'Regional Transportation Commission of Washoe County'
 'Greenville Transit Authority' 'Victor Valley Transit Authority'
 'The Eastern Contra Costa Transit Authority'
 'Ann Arbor Area Transportation Authority'
 'Stark Area Regional Transit Authority' 'City of Shreveport'
 'City of Gainesville' 'Greater Peoria Mass Transit District'
 'Intercity Transit' 'Western Piedmont Regional Transit Authority'
 'Connecticut Department of Transportation- CTTransit Waterbury- NET'
 'City of Cedar Rapids' 'City of Santa Maria' 'University of Georgia'
 'Yuma County Intergovernmental Public Transportation Authority'
 'City of Coralville' 'City of Rochester, Minnesota'
 'Macatawa Area Express Transportation Authority'
 'Muncie Indiana Transit System' 'City of Terre Haute'
 'Northern Arizona Intergovernmental Public Transportation Authority'
 'Skagit Transit' 'County of Maui' 'Sarasota County'
 'Monsey New Square Trails Corporation' 'Rockland Coaches, Inc.'
 'MTA Bus Company' 'Anaheim Transportation Network' 'City of Torrance'
 'City of Santa Monica' 'Gary Public Transportation Corporation'
 'Metropolitan Transit Authority of Harris County, Texas'
 'County of Douglas' 'MetroWest Regional Transit Authority'
 'City of Glendale' 'Pierce County Transportation Benefit Area Authority'
 'Marin County Transit District'
 'Hillsborough Area Regional Transit Authority'
 'Las Vegas Monorail Company' 'Puerto Rico Maritime Transport Authority'
 'Butler County Regional Transit Authority' 'Clermont County, Ohio'
 'Transit Authority of Northern Kentucky'
 'Mid-Ohio Regional Planning Commission' 'Delaware County Transit Board'
 'Milwaukee County' 'City of Memphis'
 'Niagara Frontier Transportation Authority'
 'Plaquemines Parish Government' 'City of Tucson' 'City of El Paso'
 'Rio Metro Regional Transit District' 'City of Fresno'
 'Miami County, Ohio' 'City of Colorado Springs' 'Lee County'
 'Golden Empire Transit District' 'Greater New Haven Transit District'
 'City of Madison' 'San Joaquin Regional Transit District'
 'Research Triangle Regional Public Transportation Authority'
 'Escambia County Board of County Commissioners, FL' 'City of Modesto'
 'Trumbull County Transit Board' 'Capital Area Transportation Authority'
 'Chatham Area Transit Authority' 'City of Santa Rosa' 'Buncombe County'
 'South Bend Public Transportation Corporation'
 'Lakeland Area Mass Transit District' 'Lane Transit District'
 'Salem Area Mass Transit District' 'Hill Country Transit District'
 'Polk County Transit Services Division - Polk County Board of County Commissioners'
 'City of Fargo' 'City of Amarillo' 'Greater Portland Transit District'
 'Spartanburg County Transportation Services' 'City of Waco'
 'Flight Line, Inc.' 'City of Racine, Wisconsin'
 'St. Cloud Metropolitan Transit Commission'
 'Southeast Alabama Regional Planning and Development Commission'
 'Bay Metropolitan Transit Authority' 'Great Falls Transit District'
 'City of Corvallis' 'City of Petaluma'
 'Berkshire Regional Transit Authority' 'County of Fayette'
 'City and County of Honolulu' 'Cape May County'
 'Okaloosa County Board of County Commissioners'
 'New Jersey Transit Corporation-45' 'Academy Lines, Inc.'
 'Trans-Bridge Lines, Inc.' 'New Jersey Transit Corporation'
 'Putnam County' 'Bergen County' 'Orange County Transportation Authority'
 'Foothill Transit' 'City of Valparaiso' 'North Township of Lake County'
 'Loudoun County' 'Cobb County' 'Enterprise Rideshare'
 'Metropolitan Atlanta Rapid Transit Authority' 'City of Peoria'
 'City of Everett' 'Omnitrans' 'County of Howard' 'City of Portland'
 'VIA Metropolitan Transit' 'Alternativa de Transporte Integrado'
 'Metropolitan Bus Authority'
 'The Transportation Management Association Group'
 'Central Oklahoma Transportation and Parking Authority'
 'Connecticut Department of Transportation -CTTRANSIT New Britain'
 'Jefferson Parish' 'Birmingham-Jefferson County Transit Authority'
 'METRO Regional Transit Authority'
 'Livermore / Amador Valley Transit Authority'
 'Denton County Transportation Authority'
 'Central New York Regional Transportation Authority' 'City of Durham'
 'Luzerne County Transportation Authority' 'City of Huntsville, Alabama'
 'City of Fort Collins' 'Lexington Transit Authority'
 'Rockford Mass Transit District' 'Ben Franklin Transit'
 'Municipality of Anchorage'
 'Central Pennsylvania Transportation Authority'
 'Kitsap County Public Transportation Benefit Area Authority'
 'City of Moorhead' 'Solano County Transit'
 'Southeast Area Transit District'
 'Southeastern Regional Transit Authority'
 'Lake County Board of County Commissioners' 'City of Yakima'
 'Duluth Transit Authority' 'City of Albany'
 'City of Jackson Transportation Authority'
 'Centre Area Transportation Authority'
 'The Tri-County Council for the Lower Eastern Shore of Maryland'
 'Altoona Metro Transit' 'City of Sheboygan' 'City of Rome'
 'Borough of Pottstown' 'Mid Mon Valley Transit Authority'
 'Suburban Transit Lines LLC' 'Port Authority Trans-Hudson Corporation'
 'Orange-Newark-Elizabeth, Inc.' 'DeCamp Bus Lines'
 'Lakeland Bus Lines, Inc.' 'Community Transit Lines, Inc.'
 'BillyBey Ferry Company, LLC' 'OBC Lines LLC'
 'Port Imperial Ferry Corporation' 'Shortline Transit LLC'
 'County of Miami-Dade' 'Fort Worth Transportation Authority'
 'Senior Citizens United Community Services of Camden County, Inc.'
 'Washington Metropolitan Area Transit Authority'
 'Gwinnett County Board of Commissioners'
 'Massachusetts Bay Transportation Authority' 'City of Phoenix'
 'City of Seattle' 'Alameda-Contra Costa Transit District'
 'Clark County Public Transportation Benefit Area Authority'
 'Sacramento Regional Transit District'
 'Central Florida Regional Transportation Authority'
 'Santa Clara Valley Transportation Authority'
 'Beaver County Transit Authority' 'Jacksonville Transportation Authority'
 'Utah Transit Authority' 'Regional Transportation Authority'
 'Greater Richmond Transit Company' 'Regional Transit Service'
 'Lehigh and Northampton Transportation Authority'
 'Capital District Transportation Authority'
 'Worcester Regional Transit Authority' 'Valley Regional Transit'
 'Collier County' 'City of Winston Salem' 'Town of Chapel Hill'
 'Corpus Christi Regional Transportation Authority'
 'North Front Range Transportation and Air Quality Planning Council'
 'Rock Island County Metropolitan Mass Transit District'
 'Cape Fear Public Transportation Authority' 'City of Tallahassee'
 'City of Sioux Falls' 'City of Ocala, Florida'
 'Rogue Valley Transportation District' 'City of Fairfield, California'
 'City of Beaumont' 'City of La Crosse' 'City of Santa Fe'

In [ ]:
num_lines = len(df_modal)
print(f"Number of lines: {num_lines}"²²²²²²²²²²²1)

Number of lines: 173302

:

In [4]:
file_path = r"C:\Users\ahmed\OneDrive\Bureau\Projet LogiOps360\logiOps360\logiOps360\Transport\Data\smart_logistics_dataset.csv"
df_smart = pd.read_csv(file_path)
df_smart.head()

,Timestamp,Asset_ID,Latitude,Longitude,Inventory_Level,Shipment_Status,Temperature,Humidity,Traffic_Status,Waiting_Time,User_Transaction_Amount,User_Purchase_Frequency,Logistics_Delay_Reason,Asset_Utilization,Demand_Forecast,Logistics_Delay
0,2024-03-20 00:11:14,Truck_7,-65.7383,11.2497,390,Delayed,27.0,67.8,Detour,38,320,4,NaN,60.1,285,1
1,2024-10-30 07:53:51,Truck_6,22.2748,-131.7086,491,In Transit,22.5,54.3,Heavy,16,439,7,Weather,80.9,174,1
2,2024-07-29 18:42:48,Truck_10,54.9232,79.5455,190,In Transit,25.2,62.2,Detour,34,355,3,NaN,99.2,260,0
3,2024-10-28 00:50:54,Truck_9,42.3900,-1.4788,330,Delivered,25.4,52.3,Heavy,37,227,5,Traffic,97.4,160,1
4,2024-09-27 15:52:58,Truck_7,-65.8477,47.9468,480,Delayed,20.5,57.2,Clear,56,197,6,NaN,71.6,270,1

In [5]:
df_smart.describe()

,Latitude,Longitude,Inventory_Level,Temperature,Humidity,Waiting_Time,User_Transaction_Amount,User_Purchase_Frequency,Asset_Utilization,Demand_Forecast,Logistics_Delay
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,-1.360093,0.837049,297.915000,23.893900,65.042200,35.062000,299.055000,5.513000,79.599100,199.284000,0.566000
std,51.997183,104.843618,113.554773,3.322178,8.753765,14.477768,117.787792,2.935379,11.631153,59.920847,0.495873
min,-89.791500,-179.820200,100.000000,18.000000,50.000000,10.000000,100.000000,1.000000,60.000000,100.000000,0.000000
25%,-46.167975,-88.448075,201.000000,21.200000,57.200000,23.000000,191.750000,3.000000,69.475000,144.000000,0.000000
50%,-4.503150,0.678300,299.000000,23.800000,65.200000,35.000000,301.500000,6.000000,79.250000,202.000000,1.000000
75%,44.502800,88.156450,399.000000,26.600000,72.400000,49.000000,405.000000,8.000000,89.425000,251.250000,1.000000
max,89.870100,179.923700,500.000000,30.000000,80.000000,60.000000,500.000000,10.000000,100.000000,300.000000,1.000000

In [6]:
null_percent = df_smart.isnull().mean() * 100
null_percent

Timestamp                   0.0
Asset_ID                    0.0
Latitude                    0.0
Longitude                   0.0
Inventory_Level             0.0
Shipment_Status             0.0
Temperature                 0.0
Humidity                    0.0
Traffic_Status              0.0
Waiting_Time                0.0
User_Transaction_Amount     0.0
User_Purchase_Frequency     0.0
Logistics_Delay_Reason     26.3
Asset_Utilization           0.0
Demand_Forecast             0.0
Logistics_Delay             0.0
dtype: float64

In [12]:
file_path2 = r"C:\Users\ahmed\OneDrive\Bureau\Projet LogiOps360\logiOps360\logiOps360\Transport\Data\Supply chain logisitcs problem.xlsx"
df_supply = pd.read_excel(file_path2)
df_supply.head()

,Order ID,Order Date,Origin Port,Carrier,TPT,Service Level,Ship ahead day count,Ship Late Day count,Customer,Product ID,Plant Code,Destination Port,Unit quantity,Weight
0,1.447296e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,808,14.30
1,1.447158e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,3188,87.94
2,1.447139e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,2331,61.20
3,1.447364e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,847,16.16
4,1.447364e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,2163,52.34

In [13]:
df_supply.describe()

,Order ID,Order Date,TPT,Ship ahead day count,Ship Late Day count,Product ID,Unit quantity,Weight
count,9.215000e+03,9215,9215.000000,9215.000000,9215.000000,9.215000e+03,9215.000000,9215.000000
mean,1.447274e+09,2013-05-26 00:00:00,1.717743,1.852306,0.039935,1.680536e+06,3202.747151,19.871688
min,1.447126e+09,2013-05-26 00:00:00,0.000000,0.000000,0.000000,1.613321e+06,235.000000,0.000000
25%,1.447197e+09,2013-05-26 00:00:00,1.000000,0.000000,0.000000,1.669702e+06,330.000000,1.407430
50%,1.447276e+09,2013-05-26 00:00:00,2.000000,3.000000,0.000000,1.683636e+06,477.000000,4.440000
75%,1.447346e+09,2013-05-26 00:00:00,2.000000,3.000000,0.000000,1.689554e+06,1275.500000,13.325673
max,1.447425e+09,2013-05-26 00:00:00,4.000000,6.000000,6.000000,1.702654e+06,561847.000000,2338.405126
std,8.381629e+04,NaN,0.630500,1.922302,0.319625,1.526593e+04,15965.622260,66.569064

In [14]:
null_percent = df_supply.isnull().mean() * 100
null_percent

Order ID                0.0
Order Date              0.0
Origin Port             0.0
Carrier                 0.0
TPT                     0.0
Service Level           0.0
Ship ahead day count    0.0
Ship Late Day count     0.0
Customer                0.0
Product ID              0.0
Plant Code              0.0
Destination Port        0.0
Unit quantity           0.0
Weight                  0.0
dtype: float64

In [16]:
file_path2 = r"C:\Users\ahmed\OneDrive\Bureau\Projet LogiOps360\logiOps360\logiOps360\Transport\Data\Transportation and Logistics Tracking Dataset..xlsx"
df_track = pd.read_excel(file_path2)
df_track

,GpsProvider,BookingID,Market/Regular,BookingID_Date,vehicle_no,Origin_Location,Destination_Location,Org_lat_lon,Des_lat_lon,Data_Ping_time,...,TRANSPORTATION_DISTANCE_IN_KM,vehicleType,Minimum_kms_to_be_covered_in_a_day,Driver_Name,Driver_MobileNo,customerID,customerNameCode,supplierID,supplierNameCode,Material Shipped
0,CONSENT TRACK,MVCV0000927/082021,Market,2020-08-17 14:59:01.000,KA590408,"TVSLSL-PUZHAL-HUB,CHENNAI,TAMIL NADU","ASHOK LEYLAND PLANT 1- HOSUR,HOSUR,KARNATAKA","13.1550,80.1960","12.7400,77.8200",2020-08-24 00:05:09,...,320.0,32 FT Single-Axle 7MT - HCV,NaN,NaN,NaN,ALLEXCHE45,Ashok leyland limited,VIJEXHOSR7,VIJAY TRANSPORT,BRACKET / GRAB HANDLE
1,VAMOSYS,VCV00014271/082021,Regular,2020-08-27 16:22:22.827,TN30BC5917,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...","DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...","12.8390,79.9540","12.8390,79.9540",2020-08-28 12:40:28,...,103.0,32 FT Multi-Axle 14MT - HCV,NaN,RAMESH,NaN,DMREXCHEUX,Daimler india commercial vehicles pvt lt,VJLEXSHE09,VJ LOGISTICS,ZB MODEL PLATE / 3143
2,CONSENT TRACK,VCV00014382/082021,Regular,2020-08-27 17:59:24.987,TN22AR2748,"LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY","LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY","11.8710,79.7390","11.8710,79.7390",2020-08-28 09:05:09,...,300.0,1 MT Tata Ace (Open Body),NaN,GIRI,NaN,LUTGCCHE06,Lucas tvs ltd,GSTEXLAK1Q,G.S. TRANSPORT,LETTERING / FUSO
3,VAMOSYS,VCV00014743/082021,Regular,2020-08-28 00:48:24.503,TN28AQ0781,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...","DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...","12.8390,79.9540","12.8390,79.9540",2020-08-28 12:40:31,...,61.0,32 FT Multi-Axle 14MT - HCV,NaN,RAVI,NaN,DMREXCHEUX,Daimler india commercial vehicles pvt lt,ARVEXNAM09,ARVINTH TRANSPORT,LU STRUT RA / RADIUS ROD
4,VAMOSYS,VCV00014744/082021,Regular,2020-08-28 01:23:19.243,TN68F1722,"LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY","LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY","11.8720,79.6320","11.8720,79.6320",2020-08-28 12:40:29,...,240.0,32 FT Multi-Axle 14MT - HCV,NaN,TAMIL,NaN,LUTGCCHE06,Lucas tvs ltd,SRTEXKOR96,SR TRANSPORTS,WISHBONE / V ROD/HDT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6875,JTECH,WDSBKTP42751,Regular,2019-03-27 17:25:33.000,KA219502,"Ramamurthy Nagar, Bangalore, Karnataka","Sahakaranagar P.O, Bangalore, Karnataka","13.007503209603689,77.665098855934886","13.068901840235711,77.590655738806618",2019-06-14 15:20:12,...,12.0,25 FT Open Body 21MT,NaN,NaN,NaN,LTLEXMUM40,Larsen & toubro limited,55556,A S TRANSPORTS,TOOL KIT SET
6876,JTECH,WDSBKTP43203,Regular,2019-03-31 15:02:34.000,KA01AE9163,"Ramamurthy Nagar, Bangalore, Karnataka","Bangalore International Airport, Bangalore, Ka...","13.007503209603689,77.665098855934886","13.196312912801169,77.708156925688726",2019-06-14 15:20:12,...,31.0,40 FT 3XL Trailer 35MT,NaN,NaN,NaN,LTLEXMUM40,Larsen & toubro limited,55556,A S TRANSPORTS,CONTROL LEVER ASSY
6877,JTECH,WDSBKTP43021,Regular,2019-03-29 18:56:26.000,KA01AE9163,"Mugabala, Bangalore Rural, Karnataka","Anekal, Bangalore, Karnataka","16.560192249175344,80.792293091599547","12.722686,77.676518",2019-06-14 15:20:12,...,49.0,40 FT 3XL Trailer 35MT,NaN,NaN,NaN,LTLEXMUM40,Larsen & toubro limited,55556,A S TRANSPORTS,SPARE PARTS AUTOMOBILE
6878,JTECH,WDSBKTP42685,Regular,2019-03-27 08:29:45.000,KA21A3643,"Mugabala, Bangalore Rural, Karnataka","Anekal, Bangalore, Karnataka","16.560192249175344,80.792293091599547","12.896896847817695,77.712223056874862",2019-06-14 15:20:12,...,49.0,40 FT 3XL Trailer 35MT,NaN,NaN,NaN,LTLEXMUM40,Larsen & toubro limited,55556,A S TRANSPORTS,SPARE PARTS AUTOMOBILE
6879,JTECH,WDSBKTP42858,Regular,2019-03-28 17:55:17.000,KA51D1317,"Mugabala, Bangalore Rural, Karnataka","Anekal, Bangalore, Karnataka","16.560192249175344,80.792293091599547","13.199089183304451,77.708554234959038",2019-06-14 15:20:12,...,49.0,40 FT 3XL Trailer 35MT,NaN,NaN,NaN,LTLEXMUM40,Larsen & toubro limited,55556,A S TRANSPORTS,SPARE PARTS AUTOMOBILE

In [17]:
df_track.describe()

,BookingID_Date,Data_Ping_time,Curr_lat,Curr_lon,TRANSPORTATION_DISTANCE_IN_KM,Minimum_kms_to_be_covered_in_a_day,Driver_MobileNo
count,6880,5927,5927.000000,5927.000000,6168.000000,2820.000000,2.691000e+03
mean,2020-02-08 05:18:40.453054208,2020-04-06 04:54:24.370193920,18.679995,78.759745,553.856282,250.239362,8.598981e+09
min,2019-03-18 12:19:22,2019-06-07 18:25:10,8.166790,69.657698,0.000000,0.000000,6.000546e+09
25%,2019-10-11 18:47:32.500000,2019-12-01 07:35:10,12.871868,76.891857,40.000000,250.000000,7.651505e+09
50%,2020-01-20 13:49:40.500000,2020-06-19 16:10:08,17.470922,77.843340,160.000000,250.000000,8.930762e+09
75%,2020-07-30 13:46:34.750000128,2020-08-10 15:52:45,23.202009,80.018999,900.000000,250.000000,9.634981e+09
max,2020-12-03 13:10:21,2020-08-28 12:40:31,32.367928,95.529550,2954.700000,275.000000,1.000000e+10
std,NaN,NaN,6.075561,4.216357,758.981836,24.315485,1.131669e+09

In [18]:
null_percent = df_track.isnull().mean() * 100
null_percent

GpsProvider                           13.851744
BookingID                              0.000000
Market/Regular                         0.000000
BookingID_Date                         0.000000
vehicle_no                             0.000000
Origin_Location                        0.000000
Destination_Location                   0.000000
Org_lat_lon                            0.000000
Des_lat_lon                            0.000000
Data_Ping_time                        13.851744
Planned_ETA                            0.000000
Current_Location                      14.011628
DestinationLocation                    0.000000
actual_eta                             0.537791
Curr_lat                              13.851744
Curr_lon                              13.851744
ontime                                62.965116
delay                                 36.889535
OriginLocation_Code                    0.043605
DestinationLocation_Code               0.392442
trip_start_date                        0.000000
trip_end_date                          2.819767
TRANSPORTATION_DISTANCE_IN_KM         10.348837
vehicleType                           11.177326
Minimum_kms_to_be_covered_in_a_day    59.011628
Driver_Name                           49.840116
Driver_MobileNo                       60.886628
customerID                             0.000000
customerNameCode                       0.000000
supplierID                             0.000000
supplierNameCode                       0.000000
Material Shipped                       0.000000
dtype: float64